server {
    listen 80;
    server_name _;

    root /app/dist;
    index index.html;
    sendfile off;

    location /api/ {
        proxy_pass http://10.20.30.2:8000/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}